### ISSUE TITLE
Is there any method to execute `symbol-bootstrap link` command remotely?

### ISSUE THREAD

**Issue by kmn** [symbol/symbol-bootstrap#290]
**Is your feature request related to a problem? Please describe.**
Some `symbol-bootstrap` commands , such as `symbol-bootstrap link`,  are not assumed that a node operator is not the private key holder of the node. 

This makes it difficult to operate nodes by other persons and/or entities; node operators are  professional server engineers but do not want to know the private key or other holder's asset secret information, although `symbol-bootstrap link` command requests to input holder's private key.

**Describe the solution you'd like**
If symbol-bootstrap command has `remote sign option`, it would work well.

1. (node operator) symbol-bootstrap command export transaction before signing in text or qr code, and pass it to the holder.
2. (holder) sign the transaction via wallet.

**Describe alternatives you've considered**
Or node operator execute an aggregate tx equal to execute `symbol-bootstrap link` command, when the main account is a multisig account.

**Comment by fboucquez** [comment]
Hi @kmn , we have implemented `--serviceProviderPublicKey` param on the `link` command. Please have a try installing the latest symbol-bootstrap@alpha.

**Comment by kmn** [comment]
@fboucquez I tried but the problem  is not solved.

The problem is `symbol-bootstrap link command requests to input holder's private key`, 


```
 symbol-bootstrap link  --serviceProviderPublicKey 1A2D488E856198BFA58D0CBB2B94C766FD8B9A1CB739982A93BCFF52BF8882EE
                         _             _         _                    _         _                      
  ___  _   _  _ __ ___  | |__    ___  | |       | |__    ___    ___  | |_  ___ | |_  _ __  __ _  _ __  
 / __|| | | || '_ ` _ \ | '_ \  / _ \ | | _____ | '_ \  / _ \  / _ \ | __|/ __|| __|| '__|/ _` || '_ \ 
 \__ \| |_| || | | | | || |_) || (_) || ||_____|| |_) || (_) || (_) || |_ \__ \| |_ | |  | (_| || |_) |
 |___/ \__, ||_| |_| |_||_.__/  \___/ |_|       |_.__/  \___/  \___/  \__||___/ \__||_|   \__,_|| .__/ 
       |___/                                                                                    |_|    
? Enter the password used to encrypt and decrypt custom presets, addresses.yml, and preset.yml files. When providing a password, private keys will be encrypted. Keep this password in a secure place! 
2021-11-11T03:14:15.916Z warn     Password has not been provided (empty text)! It's recommended to use one for security!
2021-11-11T03:14:15.958Z info     Linking nodes
2021-11-11T03:14:15.960Z info     Looking for the best node out of:  
 - http://localhost:3000
2021-11-11T03:14:15.982Z info     Connecting to node http://localhost:3000
2021-11-11T03:14:16.083Z info     Node's minFeeMultiplier is 100
2021-11-11T03:14:16.096Z info     The Service Provider Account [Address: NDAO5PB42NQXPCJVXJWRJZJUT27DVYTCIVAFMUY] is creating transactions on behalf of your node account [Address: NBNKJPCAO7TIXALVCVJNYNRLUM2ESLJUJWUDFYY].
2021-11-11T03:14:16.115Z info     Creating transactions for node: node, ca/main account: NBNKJPCAO7TIXALVCVJNYNRLUM2ESLJUJWUDFYY
2021-11-11T03:14:16.116Z info     Node node is already linked to Remote public key FE927232E7B706FC5E960BFC76C5F0985B668CAA20D95FD479973C594247D531.
2021-11-11T03:14:16.116Z info     Node node is already linked to VRF public key C476391F27F356539CE5011082DDBD8412DA1840426644EC3E19726F4A3A2F43.
? Do you want to unlink the old Voting public key A288CBE3B663B848D62D04732A95C2867FB7A1C25E01643B6BE8B20846446B44, start epoch 1, end epoch 360? Yes
2021-11-11T03:14:23.068Z info     Creating Unlink Voting Transaction from Node node to Voting public key A288CBE3B663B848D62D04732A95C2867FB7A1C25E01643B6BE8B20846446B44, start epoch 1, end epoch 360.

Service Provider private key is required when signing a transaction.
? Enter the 64 HEX private key of Service Provider account with Address: NDAO5PB42NQXPCJVXJWRJZJUT27DVYTCIVAFMUY and Public Key: 1A2D488E856198BFA58D0CBB2B94C766FD8B9A1CB739982A93BCFF52BF8882EE:  <- do not let the node operator execute this action.
```

**Comment by fboucquez** [comment]
> The problem is symbol-bootstrap link command requests to input holder's private key,

The serviceProviderPublicKey is one of your companies' public keys. Bootstrap will prompt for the private key if required. Your company account pays for the transactions fees. Your user would need to cosign in the next 48 hours in the desktop wallet.

**Comment by kmn** [comment]
I got it, that  was completely due to my misunderstanding.
Thank you for your great job,  @fboucquez !
